<?php

/**
 * @file
 * Main module file of the webform_steps_w3 module.
 *
 * The actual webform_step_w3 module has been removed. This is only a stub
 * including the functionality needed for uninstalling the module.
 */

/**
 * Copy setting from webform_steps_w3_progressbar to webform.
 */
function webform_steps_w3_migrate() {
  $sql = <<<SQL
UPDATE {webform} w INNER JOIN {webform_steps_w3_progressbar} w3 USING(nid)
SET
  w.progressbar_bar = w3.progressbar_bar,
  w.progressbar_page_number = w3.progressbar_page_number,
  w.progressbar_percent = w3.progressbar_percent,
  w.progressbar_pagebreak_labels = w3.progressbar_pagebreak_labels,
  w.progressbar_label_first = w3.progressbar_label_first
SQL;
  db_query($sql);
  drupal_set_message(t('All configurations have now been migrated to webform4. You can now safely disable and uninstall webform_steps_w3.'));
}
